fru1 = float(input('enter your budget to our shop pls '))
print(f'your budget is {fru1:.2f}')
print(f'{fru1:10}')
print(f'{fru1:04}')
print(f'{fru1:<}')
print(f'{fru1:>}')
print(f'{fru1:^}')
print(f'{fru1:+}')
print(f'{fru1:=}')
print(f'{fru1: }')
print(f'{fru1:,}')
